name: Convert Markdown into PDF
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert Markdown into PDF
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          generate-html: true
          generate-pdf: true
          config-file: .marp.yml

      - name: Rename output files
        run: |
          mv  output/README.html output/index.html

      - name: Save outputs
        uses: actions/upload-artifact@v4
        with:
          name: path
          path: ./output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output